# Generated by Django 4.2.4 on 2023-09-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0019_casting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('fka_name', models.CharField(max_length=50, null=True)),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(max_length=20)),
                ('union_status', models.CharField(choices=[('NU', 'Non Union'), ('NJ', 'Non Jursidictional'), ('U', 'Union')], max_length=2, null=True)),
                ('line_of_business', models.CharField(choices=[('FTR', 'Feature Animation'), ('TVA', 'Television Animation'), ('INT', 'Interactive'), ('DUB', 'Dubbing'), ('THM', 'Theme Park'), ('COM', 'Commercial'), ('AUB', 'Audiobook'), ('IND', 'Industrial'), ('PMO', 'Promo'), ('TRL', 'Trailer'), ('NAR', 'Narrator'), ('TOY', 'Toy')], max_length=3, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('casting_director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.casting')),
            ],
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audition.project')),
            ],
        ),
    ]
