# Generated by Django 4.2.4 on 2023-09-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0002_remove_project_rate_role_gender_role_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audition.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='enter name', max_length=25),
        ),
    ]
