# Generated by Django 4.2.4 on 2023-09-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0003_breakdown_role_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audition.project'),
        ),
    ]
