# Generated by Django 4.2.4 on 2023-09-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=1024, verbose_name='Street')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('province', models.CharField(max_length=1024, verbose_name='Province')),
                ('code', models.CharField(max_length=10, verbose_name='Zip')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=250)),
                ('dba_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=4)),
                ('area_code', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_address', models.TextField(max_length=319)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('sag_id', models.IntegerField(max_length=10)),
                ('ssn', models.IntegerField(max_length=9)),
                ('sag_union_status', models.CharField(choices=[('U', 'Union'), ('FI', 'Ficore'), ('MJ', 'Must Join'), ('TH', 'Taft Hartley'), ('NU', 'Non Union')], max_length=2)),
            ],
            bases=('account.user',),
        ),
    ]
