# Generated by Django 4.2.4 on 2023-12-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sag_id_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
