# Generated by Django 4.2.4 on 2023-09-04 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
            ],
            bases=('account.user',),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='sag_id',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='sag_union_status',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
