# Generated by Django 4.2.4 on 2023-09-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_representative_delete_address_remove_talent_sag_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='sag_id',
            field=models.IntegerField(null=True),
        ),
    ]
