# Generated by Django 4.2.4 on 2023-09-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_languages_languges_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='languages_spoken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.languges_spoken'),
        ),
    ]
