# Generated by Django 4.2.4 on 2023-09-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_talent_languages_spoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languges_Spoken',
        ),
    ]
