# Generated by Django 4.2.4 on 2023-09-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_languges_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='languages_spoken',
            field=models.ForeignKey(choices=[('ABK', 'Abkhazian'), ('AAR', 'Afar'), ('ENG', 'English'), ('FRA', 'French')], null=True, on_delete=django.db.models.deletion.CASCADE, to='account.languages'),
        ),
    ]
