# Generated by Django 4.2.4 on 2023-09-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_talent_languages_spoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='languages_spoken',
        ),
    ]
