# Generated by Django 4.2.4 on 2023-09-05 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_talent_languages_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AddField(
            model_name='talent',
            name='sag_union_status',
            field=models.CharField(choices=[('U', 'Union'), ('FI', 'Ficore'), ('MJ', 'Must Join'), ('TH', 'Taft Hartley'), ('NU', 'Non Union')], default='NU', max_length=2),
        ),
    ]
