# Generated by Django 4.2.4 on 2023-09-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_representative_employer_talent_sag_union_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='languages_spoken',
            field=models.CharField(choices=[('ABK', 'Abkhazian'), ('AAR', 'Afar'), ('ENG', 'English'), ('FRA', 'French')], default='ENG', max_length=3),
        ),
    ]
