# Generated by Django 4.2.4 on 2023-09-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_talent_languages_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ein',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='line_of_business',
            field=models.CharField(choices=[('VO', 'VO'), ('TH', 'TH'), ('OCC', 'OCC'), ('EQY', 'EQY'), ('APP', 'APP'), ('ATB', 'ATB')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='dba_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
