# Generated by Django 4.2.4 on 2023-09-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_email_address_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(to='account.talent'),
        ),
        migrations.AddField(
            model_name='company',
            name='loanout',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loanout', to='account.talent'),
        ),
    ]
