# Generated by Django 4.2.4 on 2023-09-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_company_clients_company_loanout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(null=True, to='account.talent'),
        ),
    ]
