# Generated by Django 4.2.4 on 2023-09-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_company_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(to='account.talent'),
        ),
    ]
