# Generated by Django 4.2.4 on 2023-09-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_company_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='company',
            name='loanout',
        ),
        migrations.AddField(
            model_name='talent',
            name='loanout',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loanout', to='account.company'),
        ),
        migrations.AddField(
            model_name='talent',
            name='reps',
            field=models.ManyToManyField(to='account.company'),
        ),
    ]
