# Generated by Django 4.2.4 on 2023-09-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_company_clients_remove_company_loanout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
            ],
            bases=('account.user',),
        ),
    ]
